138 cc translation
graasp/graasp-translations pull request #141
Opened 2023-03-23 12:54 UTC by clementcharmillot

Adds CC translation for the builder.

Related to:
- graasp/graasp-builder/pull/596
- graasp/graasp-library/pull/234

closes #138

2023-04-14 12:24 UTC, spaenleh requested changes
⚡ Please have a look at my comments, happy to discuss.

2023-04-14 12:24 UTC, spaenleh commented on src/langs/en/library.json
> +  "SUMMARY_ITEMS_SHOW_MORE": "+ View {{count}} more",
As said in the library review, I think you should remove these `-` and `+` and add them as icons on the button.

2023-04-14 12:24 UTC, spaenleh commented on src/langs/en/library.json
> +  "SUMMARY_ACTIONS_PREVIEW_CONTENT": "Preview Content",
Maybe simply use 
```suggestion
  "SUMMARY_ACTIONS_PREVIEW_CONTENT": "Preview",
```
as you already have the "play" button.

2023-04-14 12:24 UTC, spaenleh commented on src/langs/fr/library.json
> +  "SUMMARY_ACTIONS_PREVIEW_CONTENT": "Aperçu du contenu",
Same here
```suggestion
  "SUMMARY_ACTIONS_PREVIEW_CONTENT": "Aperçu",
```

2023-04-14 12:24 UTC, spaenleh commented on src/langs/fr/library.json
> +  "SUMMARY_ITEMS_SHOW_MORE": "+ Montrer {{count}} éléments",
Same remove `-` and `+`

2023-04-14 12:24 UTC, spaenleh commented on src/langs/fr/library.json
> +  "SUMMARY_DETAILS_NO_LANGUAGES": "Cet élément n'a pas de language défini.",
```suggestion
  "SUMMARY_DETAILS_NO_LANGUAGES": "Cet élément n'a pas de langue définie.",
```

2023-04-28 15:33 UTC, dialexo approved these changes
LGTM :heavy_check_mark: consider @spaenleh 's comments, otherwise we can just merge :+1:

2023-04-28 20:34 UTC, spaenleh approved these changes

2023-05-01 05:35 UTC, spaenleh approved these changes
LGTM ! 🚀

2023-05-01 07:34 UTC, merged