153 add edit alt text label
graasp/graasp-translations pull request #154
Opened 2023-05-16 14:40 UTC by MalinSvenberg

closes #153

2023-05-22 12:20 UTC, dialexo requested changes

2023-05-22 12:20 UTC, dialexo commented on src/langs/en/builder.json
> +  "EDIT_ITEM_IMAGE_ALT_TEXT_LABEL": "Alternative Text (for accessibility purposes)",
```suggestion
  "EDIT_ITEM_IMAGE_ALT_TEXT_LABEL": "Alternative text (for accessibility purposes)",
```

2023-05-26 08:10 UTC, pyphilia approved these changes

2023-06-14 15:08 UTC, dialexo approved these changes
Thank you 🪅

2023-06-18 21:19 UTC, merged